version: '3'
services:
  app-manager:
    build:
      context: .
      dockerfile: ./docker/app-manager/Dockerfile
    hostname: app-manager
    container_name: app-manager
    environment:
      - APP_MANAGER_URI=${APP_MANAGER_URI}
      - NIFI_URI=${NIFI_URI}
      - NIFI_USERNAME=${NIFI_USERNAME}
      - NIFI_PASSWORD=${NIFI_PASSWORD}
    ports:
      - "8082:8080"
    volumes:
      - ./docker/app-manager/app_manager:/opt/app-manager/app_manager
    depends_on:
      - nifi
  http-dummy-server:
    image: vimagick/json-server
    command: -H 0.0.0.0 -p 3000 -w access-point-sims.json --routes routes.json
    ports:
      - "3000:3000"
    volumes:
      - ./docker/http-dummy-server/ndac-responses:/data
    restart: always
  kafka:
    image: wurstmeister/kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_DIRS: "/tmp/kafka-logs"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    logging:
      driver: none
  mongo-db:
    image: mongo:latest
    hostname: mongo-db
    container_name: mongo-db
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
#      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    command: --nojournal
#    volumes:
#      - ./docker/mongo-db/data/db:/data/db
  nifi:
    build:
      context: .
      dockerfile: ./docker/nifi/Dockerfile
    hostname: nifi
    container_name: nifi
    user: root
    environment:
      SINGLE_USER_CREDENTIALS_USERNAME: ${NIFI_USERNAME}
      # Must be of 12 characters min
      SINGLE_USER_CREDENTIALS_PASSWORD: ${NIFI_PASSWORD}
      NIFI_JVM_HEAP_INIT: 4g
      NIFI_JVM_HEAP_MAX: 6g
    ports:
      - "8443:8443"
    volumes:
      - ./docker/nifi/drivers/nars:/opt/nifi/nifi-current/extensions
  node-exporter:
    image: prom/node-exporter
    hostname: node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    depends_on:
      - prometheus
  prometheus:
    image: prom/prometheus
    hostname: prometheus
    container_name: prometheus
    ports:
      - "9099:9090"
    volumes:
      - ./docker/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
  telemetry-orchestrator:
    build:
      context: .
      dockerfile: ./docker/telemetry-orchestrator/Dockerfile
    hostname: telemetry-orchestrator
    container_name: telemetry-orchestrator
    environment:
      - NIFI_URI=${NIFI_URI}
      - NIFI_USERNAME=${NIFI_USERNAME}
      - NIFI_PASSWORD=${NIFI_PASSWORD}
      - TELEMETRY_ORCHESTRATOR_URI=${TELEMETRY_ORCHESTRATOR_URI}
      - MONGO_URL=${MONGO_URL}
      - PROMETHEUS_URI=${PROMETHEUS_URI}
      - KAFKA_ENDPOINT=${KAFKA_ENDPOINT}
      - SITE_ID=${SITE_ID}
    ports:
      - "8080:8080"
    volumes:
      - ./docker/telemetry-orchestrator/telemetry_orchestrator:/opt/telemetry-orchestrator/telemetry_orchestrator
    depends_on:
      - nifi
  zookeeper:
    image: zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181"
    logging:
      driver: none

