groups:
- name: host
  rules:
  - alert: high_cpu
    annotations:
      description: Server CPU is under high load.
      summary: Server CPU is under high load.
    expr: node_load1 > 10.5
    for: 2m
    labels:
      severity: critical
