groups:
- name: targets
  rules:
  # Alert for any instance that is unreachable for >2 minutes.x
  - alert: service_down
    expr: up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "The instance {{ $labels.instance }} of job {{ $labels.job }} has been down for more than 2 minutes."